In [52]:
import numpy as np

from ipynb.fs.full.pathfinding_algorithms import *

In [53]:
m = np.array([
    [1, 1, 1, 1, 1],
    [1, 5, 5, 5, 1],
    [1, 5, 5, 5, 1],
    [1, 5, 5, 5, 1],
    [1, 1, 1, 1, 1],
])

In [69]:
def string_method(matrix, start, end):
    # assign x- and y-values to variables
    first_x, last_x = start[0], end[0]
    isXFlipped, isYFlipped = False, False

    # if start node is larger, flip the two, then set bool for flipping to True
    if start[0] > end[0]:
        first_x = end[0]
        last_x = start[0]
        isXFlipped = True

    if start[1] > end[1]:
        first_y = end[1]
        last_y = start[1]
        isYFlipped = True

    # create x- and y-value array
    x_values = np.arange(first_x, last_x + 1)
    y_values = np.arange(first_y, last_y + 1)

    # add padding if len(x_values) != len(y_values)
    if len(x_values) < len(y_values):
        x_values = np.pad(x_values, (0, len(y_values) - len(x_values)), mode='edge')
    elif len(x_values) > len(y_values):
        y_values = np.pad(y_values, (0, len(x_values) - len(y_values)), mode='edge')

    # flip the array if needed
    if isXFlipped: x_values = x_values[::-1]
    if isYFlipped: y_values = y_values[::-1]

    initial_string = np.dstack((x_values, y_values))

    print(initial_string)

    for arr in initial_string:
        for pair in arr:
            matrix[pair[0], pair[1]] = 0

    print(matrix)

In [ ]:
print(m)

In [ ]:
string_method(m, (0, 4), (4, 1))

[[[0 4]
  [1 4]
  [2 3]
  [3 2]
  [4 1]]]
[[1 1 1 1 0]
 [1 5 5 5 0]
 [1 5 5 0 1]
 [1 5 0 5 1]
 [1 0 1 1 1]]
